# Generated by Django 5.0.6 on 2024-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='Def', max_length=100)),
                ('number', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
