# Generated by Django 5.0.6 on 2024-06-30 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('projector', 'Projector'), ('monitor', 'Monitor'), ('system unit', 'System Unit'), ('peripherals', 'Peripherals')], default='projector', max_length=100)),
                ('number', models.CharField(default='', max_length=100)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(choices=[('ceit', 'CEIT'), ('caba', 'CABA'), ('coed', 'COED'), ('bacta', 'BACTA')], default='ceit', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('course', models.CharField(choices=[('ceit', 'CEIT'), ('caba', 'CABA'), ('coed', 'COED'), ('bacta', 'BACTA')], default='ceit', max_length=100)),
                ('student_No', models.CharField(max_length=7, unique=True)),
                ('RFID', models.CharField(max_length=10, null=True, unique=True)),
                ('pic', models.ImageField(null=True, upload_to='selfies/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.borrow_history')),
            ],
        ),
        migrations.AddField(
            model_name='borrow_history',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.items'),
        ),
        migrations.AddField(
            model_name='borrow_history',
            name='Professor_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.prof'),
        ),
        migrations.AddField(
            model_name='borrow_history',
            name='Borrower_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.students'),
        ),
    ]
