# Generated by Django 5.0.6 on 2024-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_history',
            name='Borrower_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
