# Generated by Django 5.0.6 on 2024-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item',
            field=models.CharField(choices=[('projector', 'Projector'), ('monitor', 'Monitor'), ('system unit', 'System Unit'), ('peripherals', 'Peripherals')], default='projector', max_length=100),
        ),
    ]
