# Generated by Django 5.0.6 on 2024-06-24 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_alter_items_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrower_Name', models.CharField(max_length=100)),
                ('Professor_Name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('ceit', 'CEIT'), ('caba', 'CABA'), ('coed', 'COED'), ('bacta', 'BACTA')], default='ceit', max_length=100)),
                ('Room', models.CharField(max_length=100)),
                ('Time_borrowed', models.DateTimeField(default=django.utils.timezone.now)),
                ('Time_returned', models.DateTimeField(blank=True, null=True)),
                ('Borrower_Selfie', models.ImageField(upload_to='selfies/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.items')),
            ],
        ),
    ]
