# Generated by Django 5.0.6 on 2024-06-30 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_alter_borrow_history_borrower_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_history',
            name='Date_Borrowed',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='borrow_history',
            name='Date_Returned',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='borrow_history',
            name='Exp_Time_Ret',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='borrow_history',
            name='Time_Ret',
            field=models.TimeField(null=True),
        ),
    ]
