# Generated by Django 5.0.6 on 2024-06-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0003_borrow_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(choices=[('ceit', 'CEIT'), ('caba', 'CABA'), ('coed', 'COED'), ('bacta', 'BACTA')], default='ceit', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('RFID', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('ceit', 'CEIT'), ('caba', 'CABA'), ('coed', 'COED'), ('bacta', 'BACTA')], default='ceit', max_length=100)),
                ('student_No', models.CharField(max_length=7)),
                ('Selfie', models.ImageField(upload_to='selfies/')),
            ],
        ),
        migrations.RemoveField(
            model_name='borrow_history',
            name='Borrower_Selfie',
        ),
        migrations.RemoveField(
            model_name='borrow_history',
            name='department',
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Professor_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.prof'),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Borrower_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.user'),
        ),
    ]
