# Generated by Django 5.0.6 on 2024-06-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_prof_user_remove_borrow_history_borrower_selfie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Selfie',
            field=models.ImageField(blank=True, upload_to='selfies/'),
        ),
    ]
