# Generated by Django 5.0.6 on 2024-06-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0005_alter_user_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='RFID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
    ]
