# Generated by Django 5.0.6 on 2024-06-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0006_alter_user_rfid_alter_user_selfie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='RFID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Selfie',
        ),
    ]
