# Generated by Django 5.0.6 on 2024-06-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0007_remove_user_rfid_remove_user_selfie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Students',
        ),
    ]
