# Generated by Django 5.0.6 on 2024-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0008_rename_user_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='RFID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='pic',
            field=models.ImageField(null=True, upload_to='selfies/'),
        ),
    ]
