# Generated by Django 5.0.6 on 2024-06-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0009_students_rfid_students_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_history',
            name='Exp_Time_Ret',
            field=models.TimeField(null=True),
        ),
    ]
