# Generated by Django 5.0.6 on 2024-06-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0010_borrow_history_exp_time_ret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='RFID',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_No',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
