# Generated by Django 5.0.6 on 2024-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0011_alter_students_name_alter_students_rfid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
