# Generated by Django 5.0.6 on 2024-06-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0012_items_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
