# Generated by Django 5.0.6 on 2024-06-29 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_alter_borrow_history_time_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_history',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Borrow_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.borrow_history')),
            ],
        ),
    ]
