# Generated by Django 5.0.6 on 2024-06-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0016_borrow_history_returned_borrow_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
