# Generated by Django 5.0.6 on 2024-06-29 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0017_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Borrower_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.students'),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Time_borrowed',
            field=models.TimeField(null=True),
        ),
    ]
