# Generated by Django 5.0.6 on 2024-06-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0018_students_active_alter_borrow_history_borrower_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_history',
            name='Professor_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.prof'),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Room',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
