# Generated by Django 5.0.6 on 2024-06-29 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0019_alter_borrow_history_professor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_history',
            name='Date_Borrowed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Date_Returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Time_borrowed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Time_returned',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
