# Generated by Django 5.0.6 on 2024-06-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0020_alter_borrow_history_date_borrowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_history',
            name='Borrower_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.students'),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Professor_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.prof'),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='Room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrow_history',
            name='returned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
