# Generated by Django 5.0.6 on 2024-06-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0022_remove_borrow_history_date_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_history',
            name='Exp_Time_Ret',
        ),
    ]
