# Generated by Django 5.0.6 on 2024-06-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0023_remove_borrow_history_exp_time_ret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_history',
            name='Date_Borrowed',
        ),
        migrations.RemoveField(
            model_name='borrow_history',
            name='returned',
        ),
    ]
